### ISSUE TITLE
bot moves sometimes don't sync

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#13]
Some users have to refresh after every move to see their move or the bot move in bot games specifically. Originally reported by a user using Brave, who said it worked when they switched to chrome.

**Comment by chuckdries** [comment]
Update: got another report of bot moves not syncing, this time in safari

**Comment by James-Quigley** [comment]
Likely due to socket disconnects. I've re-enabled socket long polling with https://github.com/ViciousFish/buzzwords/commit/efd56c3a8fff6c2fb5042c8f0478db1a1bf5f289 which should help alleviate the problem. As soon as we need to introduce a second server we will have to revisit this due to problems with load balancers and sticky sessions.

**Comment by chuckdries** [comment]
First person to report the issue to me reports it is fixed
